export const HUB_SOCKET_NAME = 'pandora_msg_hub';
export const PANDORA_HUB_ACTION_MSG_UP = 'PANDORA_HUB_ACTION_MSG_UP';
export const PANDORA_HUB_ACTION_MSG_DOWN = 'PANDORA_HUB_ACTION_MSG_DOWN';

export const PANDORA_HUB_ACTION_ONLINE_UP = 'PANDORA_HUB_ACTION_ONLINE_UP';
// export const PANDORA_HUB_ACTION_ONLINE_DOWN = 'PANDORA_HUB_ACTION_ONLINE_DOWN';

export const PANDORA_HUB_ACTION_OFFLINE_UP = 'PANDORA_HUB_ACTION_OFFLINE_UP';
// export const PANDORA_HUB_ACTION_OFFLINE_DOWN = 'PANDORA_HUB_ACTION_OFFLINE_DOWN';

export const PANDORA_HUB_ACTION_DISCOVER_UP = 'PANDORA_HUB_ACTION_DISCOVER_UP';
// export const PANDORA_HUB_ACTION_DISCOVER_DOWM = 'PANDORA_HUB_ACTION_DISCOVER_DOWM';

export const PANDORA_HUB_ACTION_LOOKUP_UP = 'PANDORA_HUB_ACTION_LOOKUP_UP';
// export const PANDORA_HUB_ACTION_LOOKUP_DOWM = 'PANDORA_HUB_ACTION_LOOKUP_DOWM';


export const TIMEOUT_OF_INVOCATON = 5000;