export const HUB_SOCKET_NAME = 'pandora_msg_hub';
export const PANDORA_HUB_ACTION_MSG_UP = 'PANDORA_HUB_ACTION_MSG_UP';
export const PANDORA_HUB_ACTION_MSG_DOWN = 'PANDORA_HUB_ACTION_MSG_DOWN';

export const PANDORA_HUB_ACTION_ONLINE_UP = 'PANDORA_HUB_ACTION_ONLINE_UP';
// export const PANDORA_HUB_ACTION_ONLINE_DOWN = 'PANDORA_HUB_ACTION_ONLINE_DOWN';

export const PANDORA_HUB_ACTION_OFFLINE_UP = 'PANDORA_HUB_ACTION_OFFLINE_UP';
// export const PANDORA_HUB_ACTION_OFFLINE_DOWN = 'PANDORA_HUB_ACTION_OFFLINE_DOWN';


export const PANDORA_HUB_ACTION_PUBLISH_UP = 'PANDORA_HUB_ACTION_PUBLISH_UP';
// export const PANDORA_HUB_ACTION_PUBLISH_DOWN = 'PANDORA_HUB_ACTION_PUBLISH_DOWN';

export const PANDORA_HUB_ACTION_UNPUBLISH_UP = 'PANDORA_HUB_ACTION_UNPUBLISH_UP';
// export const PANDORA_HUB_ACTION_UNPUBLISH_DOWN = 'PANDORA_HUB_ACTION_UNPUBLISH_DOWN';

export const PANDORA_HUB_ACTION_DISCOVER_UP = 'PANDORA_HUB_ACTION_DISCOVER_UP';
// export const PANDORA_HUB_ACTION_DISCOVER_DOWM = 'PANDORA_HUB_ACTION_DISCOVER_DOWM';

export const PANDORA_HUB_ACTION_LOOKUP_UP = 'PANDORA_HUB_ACTION_LOOKUP_UP';
// export const PANDORA_HUB_ACTION_LOOKUP_DOWM = 'PANDORA_HUB_ACTION_LOOKUP_DOWM';

export const TIMEOUT_OF_RESPONSE = 5000;


export const SERVICE_ACTION_INVOKE = 'SERVICE_ACTION_INVOKE';
export const SERVICE_ACTION_GET_PROPERTY = 'SERVICE_ACTION_GET_PROPERTY';
export const SERVICE_ACTION_INTROSPECT = 'SERVICE_ACTION_INTROSPECT';
