export const MetricsConstants = {
  SOCKET_FILE_NAME: 'pandora_metric',
  METRICS_PANDORA_KEY: 'PANDORA_METRIC',
  SERVER_DISCOVER_KEY_PREFIX: 'METRIC_DISCOVER_KEY',
  MESSENGER_PREFIX: 'ENDPOINT',
  MESSENGER_SPLIT: '_',
  METRICS_CLI_IPC_NAME: 'PANDORA_METRIC_CLI',
  METRICS_DEFAULT_APP: 'DEFAULT_APP',
  MESSENGER_UPLINK_KEY: 'MESSENGER_UPLINK', // 上行链路
  MESSENGER_DOWNLINK_KEY: 'MESSENGER_DOWNLINK', // 下行链路
  EVT_METRIC_CREATE: 'METRIC_CREATE', // metric 创建
  EVT_METRIC_UPDATE: 'METRIC_UPDATE', // metric 更新
  GLOBAL_METRICS_KEY: 'GLOBAL_METRICS_CLIENT', // 放在 global 上的 key
  CLIENT_TIME_OUT: 3000,  // client 调用超时时间
};

export const MessageConstants = {
  LOGGER: 'LOGGER',
  TRACE: 'TRACE'
};
